### ISSUE TITLE
Create setup-rig github action

### ISSUE THREAD

**Issue by blacksails** [rigdev/rig#709]
We are transitioning towards using the CLI for everything CI. We need a simple way to ensure it is installed in github actions.

```yaml
- uses: rigdev/setup-rig@v1
  with:
    version: 1.7.1
- run: rig capsule deploy ...
```
